<?php

declare(strict_types=1);

namespace ChristianBrown\SmartThings\Tests;

use ChristianBrown\SmartThings\Api\ApiHost;
use ChristianBrown\SmartThings\Api\AppApi;
use ChristianBrown\SmartThings\Api\CapabilityApi;
use ChristianBrown\SmartThings\Api\ChannelApi;
use ChristianBrown\SmartThings\Api\DeviceApi;
use ChristianBrown\SmartThings\Api\DeviceHealthApi;
use ChristianBrown\SmartThings\Api\DeviceHistoryApi;
use ChristianBrown\SmartThings\Api\DevicePreferenceDefinitionApi;
use ChristianBrown\SmartThings\Api\DevicePreferencesApi;
use ChristianBrown\SmartThings\Api\DeviceProfileApi;
use ChristianBrown\SmartThings\Api\DeviceStatusApi;
use ChristianBrown\SmartThings\Api\DriverApi;
use ChristianBrown\SmartThings\Api\DriverPackageUploader;
use ChristianBrown\SmartThings\Api\HostOverridingJsonApiRequestSender;
use ChristianBrown\SmartThings\Api\HubApi;
use ChristianBrown\SmartThings\Api\InstalledAppApi;
use ChristianBrown\SmartThings\Api\LocationApi;
use ChristianBrown\SmartThings\Api\LocationModeApi;
use ChristianBrown\SmartThings\Api\LocationRoomApi;
use ChristianBrown\SmartThings\Api\OrganizationApi;
use ChristianBrown\SmartThings\Api\PresentationApi;
use ChristianBrown\SmartThings\Api\RuleApi;
use ChristianBrown\SmartThings\Api\SceneApi;
use ChristianBrown\SmartThings\Api\ScheduleApi;
use ChristianBrown\SmartThings\Api\SchemaAppInviteApi;
use ChristianBrown\SmartThings\Api\SchemaConnectorApi;
use ChristianBrown\SmartThings\Api\ServiceApi;
use ChristianBrown\SmartThings\Api\SubscriptionApi;
use ChristianBrown\SmartThings\Api\TextToSpeechApi;
use ChristianBrown\SmartThings\Api\Token;
use ChristianBrown\SmartThings\Api\VirtualDeviceApi;
use ChristianBrown\SmartThings\DependencyInjection\ContainerFactory;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ApiClientRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\AppRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\CapabilityRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ChannelRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\CoreRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DeviceHealthRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DeviceHistoryRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DevicePreferenceDefinitionRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DevicePreferenceRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DeviceProfileRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DeviceRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DeviceStatusRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\DriverRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\HubRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\I18nRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\InstalledAppRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\LocationRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ModeRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\OrganizationRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\PresentationRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\RuleRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\SceneRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ScheduleRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\SchemaConnectorRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ServiceApiRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\ShapeRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\SubscriptionRegistrar;
use ChristianBrown\SmartThings\DependencyInjection\Registrar\TreeRegistrar;
use ChristianBrown\SmartThings\Serializer\ActionItemSerializer;
use ChristianBrown\SmartThings\Serializer\AlternativeItemSerializer;
use ChristianBrown\SmartThings\Serializer\AutomationForCapabilityActionsItemSerializer;
use ChristianBrown\SmartThings\Serializer\AutomationForCapabilityConditionsItemSerializer;
use ChristianBrown\SmartThings\Serializer\AutomationForCapabilitySerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusCameraImageSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusCameraOverlayIconsItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusCameraSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusItemActionsItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusItemProgressBarsItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusLightColorControlColorSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusLightColorControlSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusLightSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusProgressBarsBarItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusProgressBarsStateItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusStateBoardColorsSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusStateBoardItemSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvChannelSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvDirectionalPadCommandSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvDirectionalPadSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvVolumeCommandSerializer;
use ChristianBrown\SmartThings\Serializer\BasicPlusTvVolumeSerializer;
use ChristianBrown\SmartThings\Serializer\ButtonForTvSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityConfigurationSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityConfigurationValueSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityLocalizationRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityReferenceRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityValueForDashboardStateSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityValueForPanelSerializer;
use ChristianBrown\SmartThings\Serializer\CapabilityValueSerializer;
use ChristianBrown\SmartThings\Serializer\ChannelCreateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\ChannelUpdateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CreateAppRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CreateCapabilityPresentationRequestDetailViewItemSerializer;
use ChristianBrown\SmartThings\Serializer\CreateCapabilityPresentationRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CreateCapabilityRequestSerializer;
use ChristianBrown\SmartThings\Serializer\CreateDeviceProfileRequestSerializer;
use ChristianBrown\SmartThings\Serializer\DashboardForCapabilitySerializer;
use ChristianBrown\SmartThings\Serializer\DescriptionItemSerializer;
use ChristianBrown\SmartThings\Serializer\DescriptionsInAutomationSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceCategorySerializer;
use ChristianBrown\SmartThings\Serializer\DeviceCommandSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardActionInlineSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardActionSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardStateFormatInfoItemRemainingTimeSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardStateFormatInfoItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardStateFormatInfoItemTimeSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDashboardStateSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigEntryForDetailViewSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationAutomationSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationDashboardSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationDpInfoItemArgumentsItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationDpInfoItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationDpInfosItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationIconsItemBadgeItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationIconsItemProductKeysItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationIconsItemSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationRequestAutomationSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationRequestSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceConfigurationSerializer;
use ChristianBrown\SmartThings\Serializer\DeviceProfileComponentRequestSerializer;
use ChristianBrown\SmartThings\Serializer\DriverChannelCreateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\DriverChannelUpdateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\DynamicListForAutomationActionSerializer;
use ChristianBrown\SmartThings\Serializer\DynamicListForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\EmptyWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\EnumSliderForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\EnumSliderForAutomationConditionSupportedOperatorsItemSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedActionItemIdExcludeItemSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedActionItemIdSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedConditionItemIdExcludeItemAttributesItemSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedConditionItemIdExcludeItemSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedConditionItemIdSerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedDeviceActionConfigEntrySerializer;
use ChristianBrown\SmartThings\Serializer\ExcludedDeviceConditionConfigEntrySerializer;
use ChristianBrown\SmartThings\Serializer\GenerateAppOauthRequestSerializer;
use ChristianBrown\SmartThings\Serializer\GroupVisibleConditionsSerializer;
use ChristianBrown\SmartThings\Serializer\HubDeviceUpdateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\HubDriverInstallRequestSerializer;
use ChristianBrown\SmartThings\Serializer\ListForArgumentSerializer;
use ChristianBrown\SmartThings\Serializer\ListForAutomationActionSerializer;
use ChristianBrown\SmartThings\Serializer\ListForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\ListForDetailViewSerializer;
use ChristianBrown\SmartThings\Serializer\ListWithAvailableSizeCommandSerializer;
use ChristianBrown\SmartThings\Serializer\ListWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\ListWithAvailableSizeStateSerializer;
use ChristianBrown\SmartThings\Serializer\MultiArgCommandArgumentsItemSerializer;
use ChristianBrown\SmartThings\Serializer\MultiArgCommandSerializer;
use ChristianBrown\SmartThings\Serializer\NumberFieldForArgumentSerializer;
use ChristianBrown\SmartThings\Serializer\NumberFieldForAutomationActionSerializer;
use ChristianBrown\SmartThings\Serializer\NumberFieldForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\NumberFieldSerializer;
use ChristianBrown\SmartThings\Serializer\PanelForDeviceConfigItemsItemSerializer;
use ChristianBrown\SmartThings\Serializer\PanelForDeviceConfigSerializer;
use ChristianBrown\SmartThings\Serializer\PanelItemForCapabilitySerializer;
use ChristianBrown\SmartThings\Serializer\PatchItemSerializer;
use ChristianBrown\SmartThings\Serializer\PlayPauseCommandSerializer;
use ChristianBrown\SmartThings\Serializer\PlayPauseSerializer;
use ChristianBrown\SmartThings\Serializer\PlayPauseStateSerializer;
use ChristianBrown\SmartThings\Serializer\PlayStopCommandSerializer;
use ChristianBrown\SmartThings\Serializer\PlayStopSerializer;
use ChristianBrown\SmartThings\Serializer\PlayStopStateSerializer;
use ChristianBrown\SmartThings\Serializer\PlayTextRequestSerializer;
use ChristianBrown\SmartThings\Serializer\PreferenceDefinitionSerializer;
use ChristianBrown\SmartThings\Serializer\PreferenceLocalizationRequestSerializer;
use ChristianBrown\SmartThings\Serializer\PreferenceRequestSerializer;
use ChristianBrown\SmartThings\Serializer\PresentationSettingsSerializer;
use ChristianBrown\SmartThings\Serializer\PresentationSettingsTemperatureConversionsItemSerializer;
use ChristianBrown\SmartThings\Serializer\PushButtonSerializer;
use ChristianBrown\SmartThings\Serializer\PushButtonWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\RestrictionSerializer;
use ChristianBrown\SmartThings\Serializer\RuleRequestSerializer;
use ChristianBrown\SmartThings\Serializer\SchemaAppCreateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\SchemaAppInviteRequestSerializer;
use ChristianBrown\SmartThings\Serializer\SchemaAppUpdateRequestSerializer;
use ChristianBrown\SmartThings\Serializer\SchemaOauthCredentialsRequestSerializer;
use ChristianBrown\SmartThings\Serializer\ServiceSubscriptionRequestSerializer;
use ChristianBrown\SmartThings\Serializer\SliderForArgumentSerializer;
use ChristianBrown\SmartThings\Serializer\SliderForAutomationActionSerializer;
use ChristianBrown\SmartThings\Serializer\SliderForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\SliderForLightSerializer;
use ChristianBrown\SmartThings\Serializer\SliderTypeSerializer;
use ChristianBrown\SmartThings\Serializer\SliderWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\StandbyPowerSwitchForDashboardSerializer;
use ChristianBrown\SmartThings\Serializer\StandbyPowerSwitchForDashboardStateSerializer;
use ChristianBrown\SmartThings\Serializer\StandbyPowerSwitchSerializer;
use ChristianBrown\SmartThings\Serializer\StateItemSerializer;
use ChristianBrown\SmartThings\Serializer\StatelessPowerToggleForDashboardSerializer;
use ChristianBrown\SmartThings\Serializer\StateSerializer;
use ChristianBrown\SmartThings\Serializer\StateWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\StepperSerializer;
use ChristianBrown\SmartThings\Serializer\StepperWithAvailableSizeCommandSerializer;
use ChristianBrown\SmartThings\Serializer\StepperWithAvailableSizeSerializer;
use ChristianBrown\SmartThings\Serializer\StepperWithAvailableSizeStateSerializer;
use ChristianBrown\SmartThings\Serializer\SupportedValuesForDynamicListSerializer;
use ChristianBrown\SmartThings\Serializer\SupportedValuesForDynamicListValueMapSerializer;
use ChristianBrown\SmartThings\Serializer\SwitchControlSerializer;
use ChristianBrown\SmartThings\Serializer\SwitchForDashboardSerializer;
use ChristianBrown\SmartThings\Serializer\TextButtonButtonsItemSerializer;
use ChristianBrown\SmartThings\Serializer\TextButtonSerializer;
use ChristianBrown\SmartThings\Serializer\TextFieldForArgumentSerializer;
use ChristianBrown\SmartThings\Serializer\TextFieldForAutomationActionSerializer;
use ChristianBrown\SmartThings\Serializer\TextFieldForAutomationConditionSerializer;
use ChristianBrown\SmartThings\Serializer\TextFieldSerializer;
use ChristianBrown\SmartThings\Serializer\ToggleSwitchForDashboardCommandSerializer;
use ChristianBrown\SmartThings\Serializer\ToggleSwitchForDashboardSerializer;
use ChristianBrown\SmartThings\Serializer\ToggleSwitchForDashboardStateSerializer;
use ChristianBrown\SmartThings\Serializer\ToggleSwitchSerializer;
use ChristianBrown\SmartThings\Serializer\TtsRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateAppOauthRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateAppRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateAppSettingsRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateCapabilityPresentationRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateCapabilityRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateDeviceProfileRequestSerializer;
use ChristianBrown\SmartThings\Serializer\UpdateSignatureTypeRequestSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionBaseSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionForColorItemReferToSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionForColorItemSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionForDashboardStateSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionForDetailViewSerializer;
use ChristianBrown\SmartThings\Serializer\VisibleConditionSerializer;
use ChristianBrown\SmartThings\SmartThings;
use ChristianBrown\SmartThings\Transformer\ActionItemTransformer;
use ChristianBrown\SmartThings\Transformer\ActionListItemTransformer;
use ChristianBrown\SmartThings\Transformer\ActionsArrayItemTransformer;
use ChristianBrown\SmartThings\Transformer\AlternativeItemTransformer;
use ChristianBrown\SmartThings\Transformer\AppDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\AppDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\AppOauthTransformer;
use ChristianBrown\SmartThings\Transformer\AppSettingsTransformer;
use ChristianBrown\SmartThings\Transformer\AppsTransformer;
use ChristianBrown\SmartThings\Transformer\AppTransformer;
use ChristianBrown\SmartThings\Transformer\AppUiSettingsTransformer;
use ChristianBrown\SmartThings\Transformer\AttributeStateTransformer;
use ChristianBrown\SmartThings\Transformer\AttributeValueTransformer;
use ChristianBrown\SmartThings\Transformer\AutomationForCapabilityActionsItemTransformer;
use ChristianBrown\SmartThings\Transformer\AutomationForCapabilityConditionsItemTransformer;
use ChristianBrown\SmartThings\Transformer\AutomationForCapabilityTransformer;
use ChristianBrown\SmartThings\Transformer\AutomationListItemTransformer;
use ChristianBrown\SmartThings\Transformer\AutomationTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusCameraImageTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusCameraOverlayIconsItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusCameraTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusItemActionsItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusItemForPresentationTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusItemProgressBarsItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusLightColorControlColorTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusLightColorControlTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusLightTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusProgressBarsBarItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusProgressBarsStateItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusStateBoardColorsTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusStateBoardItemTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvChannelTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvDirectionalPadCommandTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvDirectionalPadTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvVolumeCommandTransformer;
use ChristianBrown\SmartThings\Transformer\BasicPlusTvVolumeTransformer;
use ChristianBrown\SmartThings\Transformer\BleD2DDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\ButtonForTvTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilitiesTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityConfigurationTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityConfigurationValueTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityNamespacesTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityNamespaceTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityPresentationDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityPresentationTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilitySubscriptionDetailTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityValueForDashboardStateTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityValueForPanelTransformer;
use ChristianBrown\SmartThings\Transformer\CapabilityValueTransformer;
use ChristianBrown\SmartThings\Transformer\ChannelDriversTransformer;
use ChristianBrown\SmartThings\Transformer\ChannelDriverTransformer;
use ChristianBrown\SmartThings\Transformer\ChannelsTransformer;
use ChristianBrown\SmartThings\Transformer\ChannelTransformer;
use ChristianBrown\SmartThings\Transformer\ClustersTransformer;
use ChristianBrown\SmartThings\Transformer\CommandClassesTransformer;
use ChristianBrown\SmartThings\Transformer\CommandMappingsTransformer;
use ChristianBrown\SmartThings\Transformer\CommandMappingTransformer;
use ChristianBrown\SmartThings\Transformer\ConvertedTtsTransformer;
use ChristianBrown\SmartThings\Transformer\CreateAppResponseTransformer;
use ChristianBrown\SmartThings\Transformer\CreateCapabilityPresentationRequestDetailViewItemTransformer;
use ChristianBrown\SmartThings\Transformer\CreateDeviceConfigRequestTransformer;
use ChristianBrown\SmartThings\Transformer\CronScheduleTransformer;
use ChristianBrown\SmartThings\Transformer\DashboardForCapabilityTransformer;
use ChristianBrown\SmartThings\Transformer\DashboardTransformer;
use ChristianBrown\SmartThings\Transformer\DescriptionItemTransformer;
use ChristianBrown\SmartThings\Transformer\DescriptionsInAutomationTransformer;
use ChristianBrown\SmartThings\Transformer\DetailViewListItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceCapabilityReferenceTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceCategoryTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceCommandResultsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceCommandResultTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceComponentCapabilitiesTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceComponentCapabilityTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceComponentsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceComponentTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardActionInlineTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardActionTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardStateFormatInfoItemRemainingTimeTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardStateFormatInfoItemTimeTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardStateFormatInfoItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDashboardStateTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigEntryForDetailViewTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationAutomationTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationDashboardTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationDpInfoItemArgumentsItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationDpInfoItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationDpInfosItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationIconsItemBadgeItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationIconsItemProductKeysItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationIconsItemTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationRequestAutomationTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceConfigurationTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceHealthDetailTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceHealthTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceHistoryEventsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceHistoryEventTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceIntegrationProfileKeyTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceLifecycleDetailTransformer;
use ChristianBrown\SmartThings\Transformer\DevicePreferenceDefinitionsTransformer;
use ChristianBrown\SmartThings\Transformer\DevicePreferenceDefinitionTransformer;
use ChristianBrown\SmartThings\Transformer\DevicePreferencesTransformer;
use ChristianBrown\SmartThings\Transformer\DevicePreferenceTransformer;
use ChristianBrown\SmartThings\Transformer\DevicePresentationTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceProfileComponentTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceProfileDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceProfileReferenceTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceProfilesTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceProfileTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceRelationshipTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceRestrictionTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceResultsTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusBatteryBatteryTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusBatteryTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusRelativeHumidityMeasurementHumidityTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusRelativeHumidityMeasurementTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusTemperatureMeasurementTemperatureTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusTemperatureMeasurementTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceStatusTransformer;
use ChristianBrown\SmartThings\Transformer\DevicesTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceSubscriptionDetailTransformer;
use ChristianBrown\SmartThings\Transformer\DeviceTransformer;
use ChristianBrown\SmartThings\Transformer\DriverDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\DriverFingerprintTransformer;
use ChristianBrown\SmartThings\Transformer\DriverPermissionTransformer;
use ChristianBrown\SmartThings\Transformer\DriversTransformer;
use ChristianBrown\SmartThings\Transformer\DriverTransformer;
use ChristianBrown\SmartThings\Transformer\DthDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\DynamicListForAutomationActionTransformer;
use ChristianBrown\SmartThings\Transformer\DynamicListForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\EdgeChildDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\EdgeDriverSupportedEndpointAppsAppsItemTransformer;
use ChristianBrown\SmartThings\Transformer\EdgeDriverSupportedEndpointAppsTransformer;
use ChristianBrown\SmartThings\Transformer\EmptyForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\EmptyWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\EnumSliderForAutomationConditionSupportedOperatorsItemTransformer;
use ChristianBrown\SmartThings\Transformer\EnumSliderForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedActionItemIdExcludeItemTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedActionItemIdTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedActionItemTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedConditionItemIdExcludeItemAttributesItemTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedConditionItemIdExcludeItemTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedConditionItemIdTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedConditionItemTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedDeviceActionConfigEntryTransformer;
use ChristianBrown\SmartThings\Transformer\ExcludedDeviceConditionConfigEntryTransformer;
use ChristianBrown\SmartThings\Transformer\GenerateAppOauthResponseTransformer;
use ChristianBrown\SmartThings\Transformer\GroupDeviceDetailsDevicesItemComponentsItemTransformer;
use ChristianBrown\SmartThings\Transformer\GroupDeviceDetailsDevicesItemTransformer;
use ChristianBrown\SmartThings\Transformer\GroupDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\GroupVisibleConditionsTransformer;
use ChristianBrown\SmartThings\Transformer\HubCharacteristicsTransformer;
use ChristianBrown\SmartThings\Transformer\HubDeviceDetailsHubDataHub2hubSupportMatrixCapabilitiesItemTransformer;
use ChristianBrown\SmartThings\Transformer\HubDeviceDetailsHubDataHub2hubSupportMatrixTransformer;
use ChristianBrown\SmartThings\Transformer\HubDeviceDetailsHubDataTransformer;
use ChristianBrown\SmartThings\Transformer\HubDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\HubDriverTransformer;
use ChristianBrown\SmartThings\Transformer\HubEnrolledChannelsTransformer;
use ChristianBrown\SmartThings\Transformer\HubEnrolledChannelTransformer;
use ChristianBrown\SmartThings\Transformer\HubHealthDetailTransformer;
use ChristianBrown\SmartThings\Transformer\HubInstalledDriversTransformer;
use ChristianBrown\SmartThings\Transformer\HubInstalledDriverTransformer;
use ChristianBrown\SmartThings\Transformer\HubTransformer;
use ChristianBrown\SmartThings\Transformer\IconImageTransformer;
use ChristianBrown\SmartThings\Transformer\IdLessHealthStateTransformer;
use ChristianBrown\SmartThings\Transformer\IndoorMapTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppConfigsTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppConfigTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppIconImageTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppsTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledAppUiTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledSchemaAppDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledSchemaAppsTransformer;
use ChristianBrown\SmartThings\Transformer\InstalledSchemaAppTransformer;
use ChristianBrown\SmartThings\Transformer\IrDeviceDetailsFunctionCodesTransformer;
use ChristianBrown\SmartThings\Transformer\IrDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\LambdaSmartAppTransformer;
use ChristianBrown\SmartThings\Transformer\LanDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\LanguageItemTransformer;
use ChristianBrown\SmartThings\Transformer\ListForArgumentTransformer;
use ChristianBrown\SmartThings\Transformer\ListForAutomationActionTransformer;
use ChristianBrown\SmartThings\Transformer\ListForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\ListForDetailViewTransformer;
use ChristianBrown\SmartThings\Transformer\ListForPanelItemCommandTransformer;
use ChristianBrown\SmartThings\Transformer\ListForPanelItemStateTransformer;
use ChristianBrown\SmartThings\Transformer\ListForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\ListWithAvailableSizeCommandTransformer;
use ChristianBrown\SmartThings\Transformer\ListWithAvailableSizeStateTransformer;
use ChristianBrown\SmartThings\Transformer\ListWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\LocaleReferencesTransformer;
use ChristianBrown\SmartThings\Transformer\LocaleReferenceTransformer;
use ChristianBrown\SmartThings\Transformer\LocalizationTransformer;
use ChristianBrown\SmartThings\Transformer\LocationDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\LocationParentTransformer;
use ChristianBrown\SmartThings\Transformer\LocationRoomDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\LocationRoomsTransformer;
use ChristianBrown\SmartThings\Transformer\LocationRoomTransformer;
use ChristianBrown\SmartThings\Transformer\LocationsTransformer;
use ChristianBrown\SmartThings\Transformer\LocationTransformer;
use ChristianBrown\SmartThings\Transformer\MatterDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\MatterEndpointDeviceTypeTransformer;
use ChristianBrown\SmartThings\Transformer\MatterEndpointTransformer;
use ChristianBrown\SmartThings\Transformer\MatterVersionTransformer;
use ChristianBrown\SmartThings\Transformer\ModesTransformer;
use ChristianBrown\SmartThings\Transformer\ModeSubscriptionDetailTransformer;
use ChristianBrown\SmartThings\Transformer\ModeTransformer;
use ChristianBrown\SmartThings\Transformer\MqttDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\MultiArgCommandArgumentsItemTransformer;
use ChristianBrown\SmartThings\Transformer\MultiArgCommandTransformer;
use ChristianBrown\SmartThings\Transformer\NoticeTransformer;
use ChristianBrown\SmartThings\Transformer\NumberFieldForArgumentTransformer;
use ChristianBrown\SmartThings\Transformer\NumberFieldForAutomationActionTransformer;
use ChristianBrown\SmartThings\Transformer\NumberFieldForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\NumberFieldTransformer;
use ChristianBrown\SmartThings\Transformer\OcfDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\OrganizationsTransformer;
use ChristianBrown\SmartThings\Transformer\OrganizationTransformer;
use ChristianBrown\SmartThings\Transformer\OwnerTransformer;
use ChristianBrown\SmartThings\Transformer\PageLinksTransformer;
use ChristianBrown\SmartThings\Transformer\PageLinkTransformer;
use ChristianBrown\SmartThings\Transformer\PanelForDeviceConfigItemsItemTransformer;
use ChristianBrown\SmartThings\Transformer\PanelForDeviceConfigTransformer;
use ChristianBrown\SmartThings\Transformer\PanelForDevicePresentationItemsItemTransformer;
use ChristianBrown\SmartThings\Transformer\PanelForDevicePresentationTransformer;
use ChristianBrown\SmartThings\Transformer\PanelItemForCapabilityTransformer;
use ChristianBrown\SmartThings\Transformer\PatchItemTransformer;
use ChristianBrown\SmartThings\Transformer\PlayedTextTransformer;
use ChristianBrown\SmartThings\Transformer\PlayPauseCommandTransformer;
use ChristianBrown\SmartThings\Transformer\PlayPauseStateTransformer;
use ChristianBrown\SmartThings\Transformer\PlayPauseTransformer;
use ChristianBrown\SmartThings\Transformer\PlayStopCommandTransformer;
use ChristianBrown\SmartThings\Transformer\PlayStopStateTransformer;
use ChristianBrown\SmartThings\Transformer\PlayStopTransformer;
use ChristianBrown\SmartThings\Transformer\PoCodesTransformer;
use ChristianBrown\SmartThings\Transformer\PresentationSettingsForDevicePresentationTransformer;
use ChristianBrown\SmartThings\Transformer\PresentationSettingsTemperatureConversionsItemTransformer;
use ChristianBrown\SmartThings\Transformer\PresentationSettingsTransformer;
use ChristianBrown\SmartThings\Transformer\PresentationTransformer;
use ChristianBrown\SmartThings\Transformer\PushButtonForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\PushButtonTransformer;
use ChristianBrown\SmartThings\Transformer\PushButtonWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\RestrictionTransformer;
use ChristianBrown\SmartThings\Transformer\RoomIndoorMapTransformer;
use ChristianBrown\SmartThings\Transformer\RulesTransformer;
use ChristianBrown\SmartThings\Transformer\RuleTransformer;
use ChristianBrown\SmartThings\Transformer\SceneLifecycleDetailTransformer;
use ChristianBrown\SmartThings\Transformer\ScenesTransformer;
use ChristianBrown\SmartThings\Transformer\SceneTransformer;
use ChristianBrown\SmartThings\Transformer\ScheduleDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\SchedulesTransformer;
use ChristianBrown\SmartThings\Transformer\ScheduleTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppInviteAcceptanceTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppInvitePageTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppInviteReceiptTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppInviteStatusTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppInviteTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppReceiptTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppsTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaAppTransformer;
use ChristianBrown\SmartThings\Transformer\SchemaPageTransformer;
use ChristianBrown\SmartThings\Transformer\SecurityArmStateDetailTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityDataAlertItemLastUpdateTimeTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityDataAlertItemSeverityTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityDataAlertItemTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityDataDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityDataTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceCapabilityNamesTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceLocationInfoSubscriptionsTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceLocationInfoSubscriptionTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceLocationInfoTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceMeasurementsTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceMeasurementTransformer;
use ChristianBrown\SmartThings\Transformer\ServiceSubscriptionReceiptTransformer;
use ChristianBrown\SmartThings\Transformer\SliderForArgumentTransformer;
use ChristianBrown\SmartThings\Transformer\SliderForAutomationActionTransformer;
use ChristianBrown\SmartThings\Transformer\SliderForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\SliderForLightTransformer;
use ChristianBrown\SmartThings\Transformer\SliderForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\SliderTypeTransformer;
use ChristianBrown\SmartThings\Transformer\SliderWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\StandbyPowerSwitchForDashboardStateTransformer;
use ChristianBrown\SmartThings\Transformer\StandbyPowerSwitchForDashboardTransformer;
use ChristianBrown\SmartThings\Transformer\StandbyPowerSwitchTransformer;
use ChristianBrown\SmartThings\Transformer\StateForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\StateItemTransformer;
use ChristianBrown\SmartThings\Transformer\StatelessPowerToggleForDashboardTransformer;
use ChristianBrown\SmartThings\Transformer\StatesArrayItemTransformer;
use ChristianBrown\SmartThings\Transformer\StateTransformer;
use ChristianBrown\SmartThings\Transformer\StateWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\StepperForPanelItemCommandTransformer;
use ChristianBrown\SmartThings\Transformer\StepperForPanelItemStateTransformer;
use ChristianBrown\SmartThings\Transformer\StepperForPanelItemTransformer;
use ChristianBrown\SmartThings\Transformer\StepperTransformer;
use ChristianBrown\SmartThings\Transformer\StepperWithAvailableSizeCommandTransformer;
use ChristianBrown\SmartThings\Transformer\StepperWithAvailableSizeStateTransformer;
use ChristianBrown\SmartThings\Transformer\StepperWithAvailableSizeTransformer;
use ChristianBrown\SmartThings\Transformer\SubscriptionDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\SubscriptionsTransformer;
use ChristianBrown\SmartThings\Transformer\SubscriptionTransformer;
use ChristianBrown\SmartThings\Transformer\SupportedValuesForDynamicListTransformer;
use ChristianBrown\SmartThings\Transformer\SupportedValuesForDynamicListValueMapTransformer;
use ChristianBrown\SmartThings\Transformer\SwitchControlTransformer;
use ChristianBrown\SmartThings\Transformer\SwitchForDashboardTransformer;
use ChristianBrown\SmartThings\Transformer\TemperatureConversionsItemForDevicePresentationTransformer;
use ChristianBrown\SmartThings\Transformer\TextButtonButtonsItemTransformer;
use ChristianBrown\SmartThings\Transformer\TextButtonTransformer;
use ChristianBrown\SmartThings\Transformer\TextFieldForArgumentTransformer;
use ChristianBrown\SmartThings\Transformer\TextFieldForAutomationActionTransformer;
use ChristianBrown\SmartThings\Transformer\TextFieldForAutomationConditionTransformer;
use ChristianBrown\SmartThings\Transformer\TextFieldTransformer;
use ChristianBrown\SmartThings\Transformer\ToggleSwitchForDashboardCommandTransformer;
use ChristianBrown\SmartThings\Transformer\ToggleSwitchForDashboardStateTransformer;
use ChristianBrown\SmartThings\Transformer\ToggleSwitchForDashboardTransformer;
use ChristianBrown\SmartThings\Transformer\ToggleSwitchTransformer;
use ChristianBrown\SmartThings\Transformer\TtsInfoTransformer;
use ChristianBrown\SmartThings\Transformer\TtsVoiceTransformer;
use ChristianBrown\SmartThings\Transformer\ViperAppLinksTransformer;
use ChristianBrown\SmartThings\Transformer\ViperDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\VirtualDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionBaseTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionForColorItemReferToTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionForColorItemTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionForDashboardStateTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionForDetailViewTransformer;
use ChristianBrown\SmartThings\Transformer\VisibleConditionTransformer;
use ChristianBrown\SmartThings\Transformer\WebhookSmartAppTransformer;
use ChristianBrown\SmartThings\Transformer\ZigbeeDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\ZigbeeGenericFingerprintTransformer;
use ChristianBrown\SmartThings\Transformer\ZigbeeManufacturerFingerprintTransformer;
use ChristianBrown\SmartThings\Transformer\ZwaveDeviceDetailsTransformer;
use ChristianBrown\SmartThings\Transformer\ZWaveGenericFingerprintTransformer;
use ChristianBrown\SmartThings\Transformer\ZWaveManufacturerFingerprintTransformer;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(SmartThings::class)]
#[UsesClass(ContainerFactory::class)]
#[UsesClass(ApiClientRegistrar::class)]
#[UsesClass(AppRegistrar::class)]
#[UsesClass(CapabilityRegistrar::class)]
#[UsesClass(ChannelRegistrar::class)]
#[UsesClass(CoreRegistrar::class)]
#[UsesClass(TreeRegistrar::class)]
#[UsesClass(ShapeRegistrar::class)]
#[UsesClass(ApiHost::class)]
#[UsesClass(HostOverridingJsonApiRequestSender::class)]
#[UsesClass(DeviceHealthRegistrar::class)]
#[UsesClass(DeviceHistoryRegistrar::class)]
#[UsesClass(DevicePreferenceDefinitionRegistrar::class)]
#[UsesClass(DevicePreferenceRegistrar::class)]
#[UsesClass(DeviceProfileRegistrar::class)]
#[UsesClass(DeviceRegistrar::class)]
#[UsesClass(DeviceStatusRegistrar::class)]
#[UsesClass(DriverRegistrar::class)]
#[UsesClass(HubRegistrar::class)]
#[UsesClass(I18nRegistrar::class)]
#[UsesClass(InstalledAppRegistrar::class)]
#[UsesClass(LocationRegistrar::class)]
#[UsesClass(ModeRegistrar::class)]
#[UsesClass(OrganizationRegistrar::class)]
#[UsesClass(PresentationRegistrar::class)]
#[UsesClass(RuleRegistrar::class)]
#[UsesClass(SceneRegistrar::class)]
#[UsesClass(ScheduleRegistrar::class)]
#[UsesClass(SchemaConnectorRegistrar::class)]
#[UsesClass(ServiceApiRegistrar::class)]
#[UsesClass(SubscriptionRegistrar::class)]
#[UsesClass(AppApi::class)]
#[UsesClass(CapabilityApi::class)]
#[UsesClass(ChannelApi::class)]
#[UsesClass(DeviceApi::class)]
#[UsesClass(DeviceHealthApi::class)]
#[UsesClass(DeviceHistoryApi::class)]
#[UsesClass(DevicePreferenceDefinitionApi::class)]
#[UsesClass(DevicePreferencesApi::class)]
#[UsesClass(DeviceProfileApi::class)]
#[UsesClass(DeviceStatusApi::class)]
#[UsesClass(DriverApi::class)]
#[UsesClass(HubApi::class)]
#[UsesClass(InstalledAppApi::class)]
#[UsesClass(LocationApi::class)]
#[UsesClass(LocationModeApi::class)]
#[UsesClass(LocationRoomApi::class)]
#[UsesClass(OrganizationApi::class)]
#[UsesClass(PresentationApi::class)]
#[UsesClass(RuleApi::class)]
#[UsesClass(SceneApi::class)]
#[UsesClass(ScheduleApi::class)]
#[UsesClass(SchemaConnectorApi::class)]
#[UsesClass(ServiceApi::class)]
#[UsesClass(SubscriptionApi::class)]
#[UsesClass(VirtualDeviceApi::class)]
#[UsesClass(Token::class)]
#[UsesClass(AppOauthTransformer::class)]
#[UsesClass(AppSettingsTransformer::class)]
#[UsesClass(AppsTransformer::class)]
#[UsesClass(AppTransformer::class)]
#[UsesClass(CapabilitiesTransformer::class)]
#[UsesClass(CapabilityNamespacesTransformer::class)]
#[UsesClass(CapabilityNamespaceTransformer::class)]
#[UsesClass(CapabilityPresentationTransformer::class)]
#[UsesClass(CapabilityTransformer::class)]
#[UsesClass(ChannelDriversTransformer::class)]
#[UsesClass(ChannelDriverTransformer::class)]
#[UsesClass(ChannelsTransformer::class)]
#[UsesClass(ChannelTransformer::class)]
#[UsesClass(DeviceCommandResultsTransformer::class)]
#[UsesClass(DeviceCommandResultTransformer::class)]
#[UsesClass(DeviceCommandSerializer::class)]
#[UsesClass(DeviceComponentCapabilitiesTransformer::class)]
#[UsesClass(DeviceComponentCapabilityTransformer::class)]
#[UsesClass(DeviceComponentsTransformer::class)]
#[UsesClass(DeviceComponentTransformer::class)]
#[UsesClass(DeviceHealthTransformer::class)]
#[UsesClass(DeviceHistoryEventsTransformer::class)]
#[UsesClass(DeviceHistoryEventTransformer::class)]
#[UsesClass(DevicePreferenceDefinitionsTransformer::class)]
#[UsesClass(DevicePreferenceDefinitionTransformer::class)]
#[UsesClass(DevicePreferencesTransformer::class)]
#[UsesClass(DevicePreferenceTransformer::class)]
#[UsesClass(DeviceProfilesTransformer::class)]
#[UsesClass(DeviceProfileTransformer::class)]
#[UsesClass(DevicesTransformer::class)]
#[UsesClass(DriversTransformer::class)]
#[UsesClass(DriverTransformer::class)]
#[UsesClass(HubCharacteristicsTransformer::class)]
#[UsesClass(HubEnrolledChannelsTransformer::class)]
#[UsesClass(HubEnrolledChannelTransformer::class)]
#[UsesClass(HubInstalledDriversTransformer::class)]
#[UsesClass(HubInstalledDriverTransformer::class)]
#[UsesClass(HubTransformer::class)]
#[UsesClass(DeviceStatusBatteryBatteryTransformer::class)]
#[UsesClass(DeviceStatusBatteryTransformer::class)]
#[UsesClass(DeviceStatusRelativeHumidityMeasurementHumidityTransformer::class)]
#[UsesClass(DeviceStatusRelativeHumidityMeasurementTransformer::class)]
#[UsesClass(DeviceStatusTemperatureMeasurementTemperatureTransformer::class)]
#[UsesClass(DeviceStatusTemperatureMeasurementTransformer::class)]
#[UsesClass(DeviceStatusTransformer::class)]
#[UsesClass(DeviceTransformer::class)]
#[UsesClass(InstalledAppConfigsTransformer::class)]
#[UsesClass(InstalledAppConfigTransformer::class)]
#[UsesClass(LocaleReferencesTransformer::class)]
#[UsesClass(LocaleReferenceTransformer::class)]
#[UsesClass(LocalizationTransformer::class)]
#[UsesClass(InstalledAppsTransformer::class)]
#[UsesClass(InstalledAppTransformer::class)]
#[UsesClass(LocationsTransformer::class)]
#[UsesClass(LocationTransformer::class)]
#[UsesClass(LocationRoomsTransformer::class)]
#[UsesClass(LocationRoomTransformer::class)]
#[UsesClass(ModesTransformer::class)]
#[UsesClass(ModeTransformer::class)]
#[UsesClass(OrganizationsTransformer::class)]
#[UsesClass(OrganizationTransformer::class)]
#[UsesClass(PresentationTransformer::class)]
#[UsesClass(RulesTransformer::class)]
#[UsesClass(RuleTransformer::class)]
#[UsesClass(ScenesTransformer::class)]
#[UsesClass(SceneTransformer::class)]
#[UsesClass(SchedulesTransformer::class)]
#[UsesClass(ScheduleTransformer::class)]
#[UsesClass(SchemaAppsTransformer::class)]
#[UsesClass(SchemaAppTransformer::class)]
#[UsesClass(SchemaPageTransformer::class)]
#[UsesClass(InstalledSchemaAppsTransformer::class)]
#[UsesClass(InstalledSchemaAppTransformer::class)]
#[UsesClass(ServiceCapabilityDataTransformer::class)]
#[UsesClass(ServiceCapabilityNamesTransformer::class)]
#[UsesClass(ServiceLocationInfoSubscriptionsTransformer::class)]
#[UsesClass(ServiceLocationInfoSubscriptionTransformer::class)]
#[UsesClass(ServiceLocationInfoTransformer::class)]
#[UsesClass(ServiceMeasurementsTransformer::class)]
#[UsesClass(ServiceMeasurementTransformer::class)]
#[UsesClass(SubscriptionsTransformer::class)]
#[UsesClass(SubscriptionTransformer::class)]
#[UsesClass(CreateAppResponseTransformer::class)]
#[UsesClass(GenerateAppOauthResponseTransformer::class)]
#[UsesClass(CreateAppRequestSerializer::class)]
#[UsesClass(UpdateAppRequestSerializer::class)]
#[UsesClass(UpdateAppSettingsRequestSerializer::class)]
#[UsesClass(UpdateAppOauthRequestSerializer::class)]
#[UsesClass(GenerateAppOauthRequestSerializer::class)]
#[UsesClass(UpdateSignatureTypeRequestSerializer::class)]
#[UsesClass(CreateCapabilityRequestSerializer::class)]
#[UsesClass(UpdateCapabilityRequestSerializer::class)]
#[UsesClass(CapabilityLocalizationRequestSerializer::class)]
#[UsesClass(CreateCapabilityPresentationRequestSerializer::class)]
#[UsesClass(UpdateCapabilityPresentationRequestSerializer::class)]
#[UsesClass(PreferenceLocalizationRequestSerializer::class)]
#[UsesClass(ChannelCreateRequestSerializer::class)]
#[UsesClass(ChannelUpdateRequestSerializer::class)]
#[UsesClass(DriverChannelCreateRequestSerializer::class)]
#[UsesClass(DriverChannelUpdateRequestSerializer::class)]
#[UsesClass(HubDriverInstallRequestSerializer::class)]
#[UsesClass(HubDeviceUpdateRequestSerializer::class)]
#[UsesClass(SchemaAppReceiptTransformer::class)]
#[UsesClass(ServiceSubscriptionReceiptTransformer::class)]
#[UsesClass(SchemaAppCreateRequestSerializer::class)]
#[UsesClass(SchemaAppUpdateRequestSerializer::class)]
#[UsesClass(SchemaOauthCredentialsRequestSerializer::class)]
#[UsesClass(ServiceSubscriptionRequestSerializer::class)]
#[UsesClass(TtsVoiceTransformer::class)]
#[UsesClass(TtsInfoTransformer::class)]
#[UsesClass(ConvertedTtsTransformer::class)]
#[UsesClass(PlayedTextTransformer::class)]
#[UsesClass(TextToSpeechApi::class)]
#[UsesClass(TtsRequestSerializer::class)]
#[UsesClass(PlayTextRequestSerializer::class)]
#[UsesClass(SchemaAppInviteReceiptTransformer::class)]
#[UsesClass(SchemaAppInviteAcceptanceTransformer::class)]
#[UsesClass(SchemaAppInviteTransformer::class)]
#[UsesClass(PageLinkTransformer::class)]
#[UsesClass(PageLinksTransformer::class)]
#[UsesClass(SchemaAppInvitePageTransformer::class)]
#[UsesClass(SchemaAppInviteStatusTransformer::class)]
#[UsesClass(SchemaAppInviteApi::class)]
#[UsesClass(SchemaAppInviteRequestSerializer::class)]
#[UsesClass(DriverPackageUploader::class)]
#[UsesClass(RuleRequestSerializer::class)]
#[UsesClass(LocationParentTransformer::class)]
#[UsesClass(LocationDetailsTransformer::class)]
#[UsesClass(RoomIndoorMapTransformer::class)]
#[UsesClass(LocationRoomDetailsTransformer::class)]
#[UsesClass(CronScheduleTransformer::class)]
#[UsesClass(ScheduleDetailsTransformer::class)]
#[UsesClass(ServiceCapabilityDataAlertItemLastUpdateTimeTransformer::class)]
#[UsesClass(ServiceCapabilityDataAlertItemSeverityTransformer::class)]
#[UsesClass(ServiceCapabilityDataAlertItemTransformer::class)]
#[UsesClass(ServiceCapabilityDataDetailsTransformer::class)]
#[UsesClass(DeviceIntegrationProfileKeyTransformer::class)]
#[UsesClass(DriverPermissionTransformer::class)]
#[UsesClass(ClustersTransformer::class)]
#[UsesClass(ZigbeeGenericFingerprintTransformer::class)]
#[UsesClass(ZigbeeManufacturerFingerprintTransformer::class)]
#[UsesClass(ZWaveManufacturerFingerprintTransformer::class)]
#[UsesClass(CommandClassesTransformer::class)]
#[UsesClass(ZWaveGenericFingerprintTransformer::class)]
#[UsesClass(DriverFingerprintTransformer::class)]
#[UsesClass(DriverDetailsTransformer::class)]
#[UsesClass(ViperAppLinksTransformer::class)]
#[UsesClass(SchemaAppDetailsTransformer::class)]
#[UsesClass(DeviceResultsTransformer::class)]
#[UsesClass(InstalledSchemaAppDetailsTransformer::class)]
#[UsesClass(DeviceSubscriptionDetailTransformer::class)]
#[UsesClass(CapabilitySubscriptionDetailTransformer::class)]
#[UsesClass(ModeSubscriptionDetailTransformer::class)]
#[UsesClass(DeviceLifecycleDetailTransformer::class)]
#[UsesClass(DeviceHealthDetailTransformer::class)]
#[UsesClass(SecurityArmStateDetailTransformer::class)]
#[UsesClass(HubHealthDetailTransformer::class)]
#[UsesClass(SceneLifecycleDetailTransformer::class)]
#[UsesClass(SubscriptionDetailsTransformer::class)]
#[UsesClass(OwnerTransformer::class)]
#[UsesClass(NoticeTransformer::class)]
#[UsesClass(InstalledAppUiTransformer::class)]
#[UsesClass(InstalledAppIconImageTransformer::class)]
#[UsesClass(InstalledAppDetailsTransformer::class)]
#[UsesClass(IconImageTransformer::class)]
#[UsesClass(LambdaSmartAppTransformer::class)]
#[UsesClass(WebhookSmartAppTransformer::class)]
#[UsesClass(AppUiSettingsTransformer::class)]
#[UsesClass(AppDetailsTransformer::class)]
#[UsesClass(IdLessHealthStateTransformer::class)]
#[UsesClass(DeviceProfileReferenceTransformer::class)]
#[UsesClass(AppDeviceDetailsTransformer::class)]
#[UsesClass(BleD2DDeviceDetailsTransformer::class)]
#[UsesClass(DthDeviceDetailsTransformer::class)]
#[UsesClass(LanDeviceDetailsTransformer::class)]
#[UsesClass(ZigbeeDeviceDetailsTransformer::class)]
#[UsesClass(ZwaveDeviceDetailsTransformer::class)]
#[UsesClass(MatterVersionTransformer::class)]
#[UsesClass(MatterEndpointDeviceTypeTransformer::class)]
#[UsesClass(MatterEndpointTransformer::class)]
#[UsesClass(MatterDeviceDetailsTransformer::class)]
#[UsesClass(HubDriverTransformer::class)]
#[UsesClass(EdgeDriverSupportedEndpointAppsAppsItemTransformer::class)]
#[UsesClass(EdgeDriverSupportedEndpointAppsTransformer::class)]
#[UsesClass(HubDeviceDetailsHubDataHub2hubSupportMatrixCapabilitiesItemTransformer::class)]
#[UsesClass(HubDeviceDetailsHubDataHub2hubSupportMatrixTransformer::class)]
#[UsesClass(HubDeviceDetailsHubDataTransformer::class)]
#[UsesClass(HubDeviceDetailsTransformer::class)]
#[UsesClass(EdgeChildDeviceDetailsTransformer::class)]
#[UsesClass(IrDeviceDetailsFunctionCodesTransformer::class)]
#[UsesClass(IrDeviceDetailsTransformer::class)]
#[UsesClass(OcfDeviceDetailsTransformer::class)]
#[UsesClass(ViperDeviceDetailsTransformer::class)]
#[UsesClass(GroupDeviceDetailsDevicesItemComponentsItemTransformer::class)]
#[UsesClass(GroupDeviceDetailsDevicesItemTransformer::class)]
#[UsesClass(GroupDeviceDetailsTransformer::class)]
#[UsesClass(AttributeValueTransformer::class)]
#[UsesClass(CommandMappingTransformer::class)]
#[UsesClass(CommandMappingsTransformer::class)]
#[UsesClass(VirtualDeviceDetailsTransformer::class)]
#[UsesClass(MqttDeviceDetailsTransformer::class)]
#[UsesClass(IndoorMapTransformer::class)]
#[UsesClass(DeviceRelationshipTransformer::class)]
#[UsesClass(DeviceDetailsTransformer::class)]
#[UsesClass(CapabilityConfigurationValueSerializer::class)]
#[UsesClass(CapabilityConfigurationSerializer::class)]
#[UsesClass(RestrictionSerializer::class)]
#[UsesClass(CapabilityReferenceRequestSerializer::class)]
#[UsesClass(DeviceCategorySerializer::class)]
#[UsesClass(DeviceProfileComponentRequestSerializer::class)]
#[UsesClass(PreferenceDefinitionSerializer::class)]
#[UsesClass(DeviceRestrictionTransformer::class)]
#[UsesClass(CapabilityConfigurationValueTransformer::class)]
#[UsesClass(CapabilityConfigurationTransformer::class)]
#[UsesClass(RestrictionTransformer::class)]
#[UsesClass(AttributeStateTransformer::class)]
#[UsesClass(DeviceCapabilityReferenceTransformer::class)]
#[UsesClass(DeviceCategoryTransformer::class)]
#[UsesClass(DeviceProfileComponentTransformer::class)]
#[UsesClass(DeviceProfileDetailsTransformer::class)]
#[UsesClass(CreateDeviceProfileRequestSerializer::class)]
#[UsesClass(UpdateDeviceProfileRequestSerializer::class)]
#[UsesClass(PreferenceRequestSerializer::class)]
#[UsesClass(AlternativeItemSerializer::class)]
#[UsesClass(StateItemSerializer::class)]
#[UsesClass(PushButtonSerializer::class)]
#[UsesClass(ToggleSwitchForDashboardCommandSerializer::class)]
#[UsesClass(ToggleSwitchForDashboardStateSerializer::class)]
#[UsesClass(ToggleSwitchForDashboardSerializer::class)]
#[UsesClass(SwitchForDashboardSerializer::class)]
#[UsesClass(StandbyPowerSwitchForDashboardStateSerializer::class)]
#[UsesClass(StandbyPowerSwitchForDashboardSerializer::class)]
#[UsesClass(StatelessPowerToggleForDashboardSerializer::class)]
#[UsesClass(PlayPauseCommandSerializer::class)]
#[UsesClass(PlayPauseStateSerializer::class)]
#[UsesClass(PlayPauseSerializer::class)]
#[UsesClass(PlayStopCommandSerializer::class)]
#[UsesClass(PlayStopStateSerializer::class)]
#[UsesClass(PlayStopSerializer::class)]
#[UsesClass(ActionItemSerializer::class)]
#[UsesClass(StepperWithAvailableSizeCommandSerializer::class)]
#[UsesClass(StepperWithAvailableSizeStateSerializer::class)]
#[UsesClass(StepperWithAvailableSizeSerializer::class)]
#[UsesClass(ListWithAvailableSizeCommandSerializer::class)]
#[UsesClass(ListWithAvailableSizeStateSerializer::class)]
#[UsesClass(ListWithAvailableSizeSerializer::class)]
#[UsesClass(PushButtonWithAvailableSizeSerializer::class)]
#[UsesClass(StateWithAvailableSizeSerializer::class)]
#[UsesClass(SliderWithAvailableSizeSerializer::class)]
#[UsesClass(EmptyWithAvailableSizeSerializer::class)]
#[UsesClass(PanelItemForCapabilitySerializer::class)]
#[UsesClass(DashboardForCapabilitySerializer::class)]
#[UsesClass(ToggleSwitchSerializer::class)]
#[UsesClass(StandbyPowerSwitchSerializer::class)]
#[UsesClass(SwitchControlSerializer::class)]
#[UsesClass(SliderTypeSerializer::class)]
#[UsesClass(TextButtonButtonsItemSerializer::class)]
#[UsesClass(TextButtonSerializer::class)]
#[UsesClass(ListForDetailViewSerializer::class)]
#[UsesClass(TextFieldSerializer::class)]
#[UsesClass(NumberFieldSerializer::class)]
#[UsesClass(StepperSerializer::class)]
#[UsesClass(StateSerializer::class)]
#[UsesClass(VisibleConditionBaseSerializer::class)]
#[UsesClass(CreateCapabilityPresentationRequestDetailViewItemSerializer::class)]
#[UsesClass(SliderForAutomationConditionSerializer::class)]
#[UsesClass(ListForAutomationConditionSerializer::class)]
#[UsesClass(SupportedValuesForDynamicListValueMapSerializer::class)]
#[UsesClass(SupportedValuesForDynamicListSerializer::class)]
#[UsesClass(DynamicListForAutomationConditionSerializer::class)]
#[UsesClass(NumberFieldForAutomationConditionSerializer::class)]
#[UsesClass(TextFieldForAutomationConditionSerializer::class)]
#[UsesClass(EnumSliderForAutomationConditionSupportedOperatorsItemSerializer::class)]
#[UsesClass(EnumSliderForAutomationConditionSerializer::class)]
#[UsesClass(AutomationForCapabilityConditionsItemSerializer::class)]
#[UsesClass(SliderForAutomationActionSerializer::class)]
#[UsesClass(ListForAutomationActionSerializer::class)]
#[UsesClass(DynamicListForAutomationActionSerializer::class)]
#[UsesClass(TextFieldForAutomationActionSerializer::class)]
#[UsesClass(NumberFieldForAutomationActionSerializer::class)]
#[UsesClass(SliderForArgumentSerializer::class)]
#[UsesClass(ListForArgumentSerializer::class)]
#[UsesClass(TextFieldForArgumentSerializer::class)]
#[UsesClass(NumberFieldForArgumentSerializer::class)]
#[UsesClass(MultiArgCommandArgumentsItemSerializer::class)]
#[UsesClass(MultiArgCommandSerializer::class)]
#[UsesClass(AutomationForCapabilityActionsItemSerializer::class)]
#[UsesClass(AutomationForCapabilitySerializer::class)]
#[UsesClass(PresentationSettingsTemperatureConversionsItemSerializer::class)]
#[UsesClass(PresentationSettingsSerializer::class)]
#[UsesClass(AlternativeItemTransformer::class)]
#[UsesClass(StateItemTransformer::class)]
#[UsesClass(PushButtonTransformer::class)]
#[UsesClass(ToggleSwitchForDashboardCommandTransformer::class)]
#[UsesClass(ToggleSwitchForDashboardStateTransformer::class)]
#[UsesClass(ToggleSwitchForDashboardTransformer::class)]
#[UsesClass(SwitchForDashboardTransformer::class)]
#[UsesClass(StandbyPowerSwitchForDashboardStateTransformer::class)]
#[UsesClass(StandbyPowerSwitchForDashboardTransformer::class)]
#[UsesClass(StatelessPowerToggleForDashboardTransformer::class)]
#[UsesClass(PlayPauseCommandTransformer::class)]
#[UsesClass(PlayPauseStateTransformer::class)]
#[UsesClass(PlayPauseTransformer::class)]
#[UsesClass(PlayStopCommandTransformer::class)]
#[UsesClass(PlayStopStateTransformer::class)]
#[UsesClass(PlayStopTransformer::class)]
#[UsesClass(ActionItemTransformer::class)]
#[UsesClass(StepperWithAvailableSizeCommandTransformer::class)]
#[UsesClass(StepperWithAvailableSizeStateTransformer::class)]
#[UsesClass(StepperWithAvailableSizeTransformer::class)]
#[UsesClass(ListWithAvailableSizeCommandTransformer::class)]
#[UsesClass(ListWithAvailableSizeStateTransformer::class)]
#[UsesClass(ListWithAvailableSizeTransformer::class)]
#[UsesClass(PushButtonWithAvailableSizeTransformer::class)]
#[UsesClass(StateWithAvailableSizeTransformer::class)]
#[UsesClass(SliderWithAvailableSizeTransformer::class)]
#[UsesClass(EmptyWithAvailableSizeTransformer::class)]
#[UsesClass(PanelItemForCapabilityTransformer::class)]
#[UsesClass(DashboardForCapabilityTransformer::class)]
#[UsesClass(ToggleSwitchTransformer::class)]
#[UsesClass(StandbyPowerSwitchTransformer::class)]
#[UsesClass(SwitchControlTransformer::class)]
#[UsesClass(SliderTypeTransformer::class)]
#[UsesClass(TextButtonButtonsItemTransformer::class)]
#[UsesClass(TextButtonTransformer::class)]
#[UsesClass(ListForDetailViewTransformer::class)]
#[UsesClass(TextFieldTransformer::class)]
#[UsesClass(NumberFieldTransformer::class)]
#[UsesClass(StepperTransformer::class)]
#[UsesClass(StateTransformer::class)]
#[UsesClass(VisibleConditionBaseTransformer::class)]
#[UsesClass(CreateCapabilityPresentationRequestDetailViewItemTransformer::class)]
#[UsesClass(SliderForAutomationConditionTransformer::class)]
#[UsesClass(ListForAutomationConditionTransformer::class)]
#[UsesClass(SupportedValuesForDynamicListValueMapTransformer::class)]
#[UsesClass(SupportedValuesForDynamicListTransformer::class)]
#[UsesClass(DynamicListForAutomationConditionTransformer::class)]
#[UsesClass(NumberFieldForAutomationConditionTransformer::class)]
#[UsesClass(TextFieldForAutomationConditionTransformer::class)]
#[UsesClass(EnumSliderForAutomationConditionSupportedOperatorsItemTransformer::class)]
#[UsesClass(EnumSliderForAutomationConditionTransformer::class)]
#[UsesClass(AutomationForCapabilityConditionsItemTransformer::class)]
#[UsesClass(SliderForAutomationActionTransformer::class)]
#[UsesClass(ListForAutomationActionTransformer::class)]
#[UsesClass(DynamicListForAutomationActionTransformer::class)]
#[UsesClass(TextFieldForAutomationActionTransformer::class)]
#[UsesClass(NumberFieldForAutomationActionTransformer::class)]
#[UsesClass(SliderForArgumentTransformer::class)]
#[UsesClass(ListForArgumentTransformer::class)]
#[UsesClass(TextFieldForArgumentTransformer::class)]
#[UsesClass(NumberFieldForArgumentTransformer::class)]
#[UsesClass(MultiArgCommandArgumentsItemTransformer::class)]
#[UsesClass(MultiArgCommandTransformer::class)]
#[UsesClass(AutomationForCapabilityActionsItemTransformer::class)]
#[UsesClass(AutomationForCapabilityTransformer::class)]
#[UsesClass(PresentationSettingsTemperatureConversionsItemTransformer::class)]
#[UsesClass(PresentationSettingsTransformer::class)]
#[UsesClass(CapabilityPresentationDetailsTransformer::class)]
#[UsesClass(DeviceConfigurationDpInfoItemArgumentsItemSerializer::class)]
#[UsesClass(DeviceConfigurationDpInfoItemArgumentsItemTransformer::class)]
#[UsesClass(DeviceConfigurationDpInfoItemSerializer::class)]
#[UsesClass(DeviceConfigurationDpInfoItemTransformer::class)]
#[UsesClass(DeviceConfigurationDpInfosItemSerializer::class)]
#[UsesClass(DeviceConfigurationDpInfosItemTransformer::class)]
#[UsesClass(VisibleConditionSerializer::class)]
#[UsesClass(VisibleConditionTransformer::class)]
#[UsesClass(DeviceConfigurationIconsItemBadgeItemSerializer::class)]
#[UsesClass(DeviceConfigurationIconsItemBadgeItemTransformer::class)]
#[UsesClass(DeviceConfigurationIconsItemProductKeysItemSerializer::class)]
#[UsesClass(DeviceConfigurationIconsItemProductKeysItemTransformer::class)]
#[UsesClass(DeviceConfigurationIconsItemSerializer::class)]
#[UsesClass(DeviceConfigurationIconsItemTransformer::class)]
#[UsesClass(CapabilityValueForDashboardStateSerializer::class)]
#[UsesClass(CapabilityValueForDashboardStateTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemRemainingTimeSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemRemainingTimeTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemTimeSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemTimeTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateFormatInfoItemTransformer::class)]
#[UsesClass(VisibleConditionForDashboardStateSerializer::class)]
#[UsesClass(VisibleConditionForDashboardStateTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardStateTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardActionInlineSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardActionInlineTransformer::class)]
#[UsesClass(DeviceConfigEntryForDashboardActionSerializer::class)]
#[UsesClass(DeviceConfigEntryForDashboardActionTransformer::class)]
#[UsesClass(BasicPlusCameraImageSerializer::class)]
#[UsesClass(BasicPlusCameraImageTransformer::class)]
#[UsesClass(BasicPlusCameraOverlayIconsItemSerializer::class)]
#[UsesClass(BasicPlusCameraOverlayIconsItemTransformer::class)]
#[UsesClass(BasicPlusCameraSerializer::class)]
#[UsesClass(BasicPlusCameraTransformer::class)]
#[UsesClass(BasicPlusTvVolumeCommandSerializer::class)]
#[UsesClass(BasicPlusTvVolumeCommandTransformer::class)]
#[UsesClass(BasicPlusTvVolumeSerializer::class)]
#[UsesClass(BasicPlusTvVolumeTransformer::class)]
#[UsesClass(ButtonForTvSerializer::class)]
#[UsesClass(ButtonForTvTransformer::class)]
#[UsesClass(BasicPlusTvChannelSerializer::class)]
#[UsesClass(BasicPlusTvChannelTransformer::class)]
#[UsesClass(BasicPlusTvDirectionalPadCommandSerializer::class)]
#[UsesClass(BasicPlusTvDirectionalPadCommandTransformer::class)]
#[UsesClass(BasicPlusTvDirectionalPadSerializer::class)]
#[UsesClass(BasicPlusTvDirectionalPadTransformer::class)]
#[UsesClass(BasicPlusTvSerializer::class)]
#[UsesClass(BasicPlusTvTransformer::class)]
#[UsesClass(SliderForLightSerializer::class)]
#[UsesClass(SliderForLightTransformer::class)]
#[UsesClass(BasicPlusLightColorControlColorSerializer::class)]
#[UsesClass(BasicPlusLightColorControlColorTransformer::class)]
#[UsesClass(BasicPlusLightColorControlSerializer::class)]
#[UsesClass(BasicPlusLightColorControlTransformer::class)]
#[UsesClass(BasicPlusLightSerializer::class)]
#[UsesClass(BasicPlusLightTransformer::class)]
#[UsesClass(BasicPlusItemActionsItemSerializer::class)]
#[UsesClass(BasicPlusItemActionsItemTransformer::class)]
#[UsesClass(VisibleConditionForColorItemReferToSerializer::class)]
#[UsesClass(VisibleConditionForColorItemReferToTransformer::class)]
#[UsesClass(VisibleConditionForColorItemSerializer::class)]
#[UsesClass(VisibleConditionForColorItemTransformer::class)]
#[UsesClass(BasicPlusStateBoardColorsSerializer::class)]
#[UsesClass(BasicPlusStateBoardColorsTransformer::class)]
#[UsesClass(BasicPlusStateBoardItemSerializer::class)]
#[UsesClass(BasicPlusStateBoardItemTransformer::class)]
#[UsesClass(BasicPlusProgressBarsStateItemSerializer::class)]
#[UsesClass(BasicPlusProgressBarsStateItemTransformer::class)]
#[UsesClass(BasicPlusProgressBarsBarItemSerializer::class)]
#[UsesClass(BasicPlusProgressBarsBarItemTransformer::class)]
#[UsesClass(BasicPlusItemProgressBarsItemSerializer::class)]
#[UsesClass(BasicPlusItemProgressBarsItemTransformer::class)]
#[UsesClass(CapabilityValueForPanelSerializer::class)]
#[UsesClass(CapabilityValueForPanelTransformer::class)]
#[UsesClass(PanelForDeviceConfigItemsItemSerializer::class)]
#[UsesClass(PanelForDeviceConfigItemsItemTransformer::class)]
#[UsesClass(PanelForDeviceConfigSerializer::class)]
#[UsesClass(PanelForDeviceConfigTransformer::class)]
#[UsesClass(BasicPlusItemSerializer::class)]
#[UsesClass(BasicPlusItemTransformer::class)]
#[UsesClass(GroupVisibleConditionsSerializer::class)]
#[UsesClass(GroupVisibleConditionsTransformer::class)]
#[UsesClass(DeviceConfigurationDashboardSerializer::class)]
#[UsesClass(DeviceConfigurationDashboardTransformer::class)]
#[UsesClass(CapabilityValueSerializer::class)]
#[UsesClass(CapabilityValueTransformer::class)]
#[UsesClass(PatchItemSerializer::class)]
#[UsesClass(PatchItemTransformer::class)]
#[UsesClass(VisibleConditionForDetailViewSerializer::class)]
#[UsesClass(VisibleConditionForDetailViewTransformer::class)]
#[UsesClass(DeviceConfigEntryForDetailViewSerializer::class)]
#[UsesClass(DeviceConfigEntryForDetailViewTransformer::class)]
#[UsesClass(ExcludedConditionItemIdExcludeItemAttributesItemSerializer::class)]
#[UsesClass(ExcludedConditionItemIdExcludeItemAttributesItemTransformer::class)]
#[UsesClass(ExcludedConditionItemIdExcludeItemSerializer::class)]
#[UsesClass(ExcludedConditionItemIdExcludeItemTransformer::class)]
#[UsesClass(ExcludedConditionItemIdSerializer::class)]
#[UsesClass(ExcludedConditionItemIdTransformer::class)]
#[UsesClass(ExcludedDeviceConditionConfigEntrySerializer::class)]
#[UsesClass(ExcludedDeviceConditionConfigEntryTransformer::class)]
#[UsesClass(ExcludedActionItemIdExcludeItemSerializer::class)]
#[UsesClass(ExcludedActionItemIdExcludeItemTransformer::class)]
#[UsesClass(ExcludedActionItemIdSerializer::class)]
#[UsesClass(ExcludedActionItemIdTransformer::class)]
#[UsesClass(ExcludedDeviceActionConfigEntrySerializer::class)]
#[UsesClass(ExcludedDeviceActionConfigEntryTransformer::class)]
#[UsesClass(DescriptionItemSerializer::class)]
#[UsesClass(DescriptionItemTransformer::class)]
#[UsesClass(DescriptionsInAutomationSerializer::class)]
#[UsesClass(DescriptionsInAutomationTransformer::class)]
#[UsesClass(DeviceConfigurationAutomationSerializer::class)]
#[UsesClass(DeviceConfigurationAutomationTransformer::class)]
#[UsesClass(DeviceConfigurationSerializer::class)]
#[UsesClass(DeviceConfigurationTransformer::class)]
#[UsesClass(DeviceConfigurationRequestAutomationSerializer::class)]
#[UsesClass(DeviceConfigurationRequestAutomationTransformer::class)]
#[UsesClass(DeviceConfigurationRequestSerializer::class)]
#[UsesClass(CreateDeviceConfigRequestTransformer::class)]
#[UsesClass(StatesArrayItemTransformer::class)]
#[UsesClass(ActionsArrayItemTransformer::class)]
#[UsesClass(StepperForPanelItemCommandTransformer::class)]
#[UsesClass(StepperForPanelItemStateTransformer::class)]
#[UsesClass(StepperForPanelItemTransformer::class)]
#[UsesClass(ListForPanelItemCommandTransformer::class)]
#[UsesClass(ListForPanelItemStateTransformer::class)]
#[UsesClass(ListForPanelItemTransformer::class)]
#[UsesClass(PushButtonForPanelItemTransformer::class)]
#[UsesClass(StateForPanelItemTransformer::class)]
#[UsesClass(SliderForPanelItemTransformer::class)]
#[UsesClass(EmptyForPanelItemTransformer::class)]
#[UsesClass(PanelForDevicePresentationItemsItemTransformer::class)]
#[UsesClass(PanelForDevicePresentationTransformer::class)]
#[UsesClass(BasicPlusItemForPresentationTransformer::class)]
#[UsesClass(DashboardTransformer::class)]
#[UsesClass(DetailViewListItemTransformer::class)]
#[UsesClass(ExcludedConditionItemTransformer::class)]
#[UsesClass(AutomationListItemTransformer::class)]
#[UsesClass(ExcludedActionItemTransformer::class)]
#[UsesClass(ActionListItemTransformer::class)]
#[UsesClass(AutomationTransformer::class)]
#[UsesClass(PoCodesTransformer::class)]
#[UsesClass(LanguageItemTransformer::class)]
#[UsesClass(TemperatureConversionsItemForDevicePresentationTransformer::class)]
#[UsesClass(PresentationSettingsForDevicePresentationTransformer::class)]
#[UsesClass(DevicePresentationTransformer::class)]
final class SmartThingsTest extends TestCase
{
    public function testConstructAcceptsCustomApiHost(): void
    {
        $smartThings = new SmartThings('token', new ApiHost('https://staging.example.test'));

        self::assertInstanceOf(DeviceApi::class, $smartThings->getDeviceApi());
    }

    public function testGetAppApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(AppApi::class, $smartThings->getAppApi());
    }

    public function testGetCapabilityApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(CapabilityApi::class, $smartThings->getCapabilityApi());
    }

    public function testGetChannelApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(ChannelApi::class, $smartThings->getChannelApi());
    }

    public function testGetDeviceApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DeviceApi::class, $smartThings->getDeviceApi());
    }

    public function testGetDeviceHealthApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DeviceHealthApi::class, $smartThings->getDeviceHealthApi());
    }

    public function testGetDeviceHistoryApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DeviceHistoryApi::class, $smartThings->getDeviceHistoryApi());
    }

    public function testGetDevicePreferenceDefinitionApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DevicePreferenceDefinitionApi::class, $smartThings->getDevicePreferenceDefinitionApi());
    }

    public function testGetDevicePreferencesApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DevicePreferencesApi::class, $smartThings->getDevicePreferencesApi());
    }

    public function testGetDeviceProfileApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DeviceProfileApi::class, $smartThings->getDeviceProfileApi());
    }

    public function testGetDeviceStatusApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DeviceStatusApi::class, $smartThings->getDeviceStatusApi());
    }

    public function testGetDriverApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(DriverApi::class, $smartThings->getDriverApi());
    }

    public function testGetHubApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(HubApi::class, $smartThings->getHubApi());
    }

    public function testGetInstalledAppApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(InstalledAppApi::class, $smartThings->getInstalledAppApi());
    }

    public function testGetLocationApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(LocationApi::class, $smartThings->getLocationApi());
    }

    public function testGetLocationModeApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(LocationModeApi::class, $smartThings->getLocationModeApi());
    }

    public function testGetLocationRoomApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(LocationRoomApi::class, $smartThings->getLocationRoomApi());
    }

    public function testGetOrganizationApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(OrganizationApi::class, $smartThings->getOrganizationApi());
    }

    public function testGetPresentationApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(PresentationApi::class, $smartThings->getPresentationApi());
    }

    public function testGetRuleApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(RuleApi::class, $smartThings->getRuleApi());
    }

    public function testGetSceneApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(SceneApi::class, $smartThings->getSceneApi());
    }

    public function testGetScheduleApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(ScheduleApi::class, $smartThings->getScheduleApi());
    }

    public function testGetSchemaAppInviteApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(SchemaAppInviteApi::class, $smartThings->getSchemaAppInviteApi());
    }

    public function testGetSchemaConnectorApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(SchemaConnectorApi::class, $smartThings->getSchemaConnectorApi());
    }

    public function testGetServiceApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(ServiceApi::class, $smartThings->getServiceApi());
    }

    public function testGetSubscriptionApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(SubscriptionApi::class, $smartThings->getSubscriptionApi());
    }

    public function testGetTextToSpeechApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(TextToSpeechApi::class, $smartThings->getTextToSpeechApi());
    }

    public function testGetVirtualDeviceApi(): void
    {
        $smartThings = new SmartThings('token');

        self::assertInstanceOf(VirtualDeviceApi::class, $smartThings->getVirtualDeviceApi());
    }
}
